language: python            # this works for Linux but is an error on macOS or Windows
matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.7
    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.7.3 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install: choco install python
      
#services: e.g. mysql 

env:
  - DJANGO_VERSION=2.2.3
#commands to install dependencies
install:
  - pip install -q Django==$DJANGO_VERSION
  #- pip install -q -r requirements.txt
  #- python setup.py -q install
jobs:
  include:
    - stage: test
      script: echo one #pytest
      script: python ./back-end/IMM/api/tests.py test
    - stage: deploy
      script: skip #./deploy
      deploy: &heroku
        provider: heroku
        app: ###
        api_key: ###$HEROKU_AUTH_TOKEN
        on: 
          branch: master

