# Generated by Django 2.0.3 on 2019-05-16 13:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('date', models.DateField(default=datetime.date(2019, 5, 16))),
                ('reason', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('startTime', models.TimeField(default=datetime.datetime.now)),
                ('endTime', models.TimeField(default=datetime.datetime.now)),
                ('date', models.DateField(default=datetime.date(2019, 5, 16))),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('speciality', models.CharField(choices=[(0, 'N/A'), (1, 'Radiologist'), (2, 'Neurologist'), (3, 'Neurosergeon'), (4, 'Physician'), (5, 'Pathologist'), (6, 'Orthopedics'), (7, 'General Surgery'), (8, 'Internal Medicine'), (9, 'Paedriatics'), (10, 'ENT')], max_length=50)),
                ('contactName', models.CharField(blank=True, max_length=50)),
                ('contactNumber', models.CharField(blank=True, max_length=20)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birthday', models.DateField(default=datetime.date(1000, 1, 1))),
                ('phone', models.CharField(max_length=20)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodType', models.CharField(choices=[('A+', 'A+ Type'), ('B+', 'B+ Type'), ('AB+', 'AB+ Type'), ('O+', 'O+ Type'), ('A-', 'A- Type'), ('B-', 'B- Type'), ('AB-', 'AB- Type'), ('O-', 'O- Type')], max_length=10)),
                ('allergy', models.CharField(max_length=100)),
                ('alzheimer', models.BooleanField()),
                ('asthma', models.BooleanField()),
                ('diabetes', models.BooleanField()),
                ('stroke', models.BooleanField()),
                ('comments', models.CharField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date(2019, 5, 16))),
                ('description', models.CharField(max_length=200)),
                ('private', models.BooleanField(default=True)),
                ('completed', models.BooleanField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dicomapp.Doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dicomapp.Hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=50)),
                ('lastname', models.CharField(blank=True, max_length=50)),
                ('insurance', models.CharField(choices=[(0, 'N/A'), (1, 'Aetna'), (2, 'United HealthCare'), (3, 'Humana'), (4, 'Celtic Healthcare'), (5, 'BlueCross BlueShield'), (6, 'Cigna'), (7, 'Emblem Healthcare'), (8, 'Amerigroup'), (9, 'Kaiser Permanente'), (10, 'Wellpoint')], max_length=50)),
                ('emergencyContactName', models.CharField(blank=True, max_length=50)),
                ('emergencyContactNumber', models.CharField(blank=True, max_length=20)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birthday', models.DateField(default=datetime.date(1000, 1, 1))),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('allergies', models.CharField(blank=True, max_length=250)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('prefHospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dicomapp.Hospital')),
            ],
        ),
        migrations.CreateModel(
            name='PatientFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dicomapp.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2019, 5, 16))),
                ('medication', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=30)),
                ('instruction', models.CharField(max_length=200)),
                ('refill', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dicomapp.Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dicomapp.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='medicaltest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dicomapp.Patient'),
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dicomapp.Patient'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dicomapp.Location'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='prefHospital',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dicomapp.Hospital'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dicomapp.Doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dicomapp.Hospital'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dicomapp.Patient'),
        ),
        migrations.AddField(
            model_name='admission',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dicomapp.Hospital'),
        ),
        migrations.AddField(
            model_name='admission',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dicomapp.Patient'),
        ),
    ]
