# Generated by Django 2.0.3 on 2019-05-16 13:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dicomapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 5, 16, 13, 42, 7, 935241, tzinfo=utc)),
        ),
    ]
