# Generated by Django 2.0.3 on 2019-05-16 13:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dicomapp', '0002_auto_20190516_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 5, 16, 13, 43, 45, 701808, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='admission',
            name='time',
            field=models.TimeField(default=datetime.datetime(2019, 5, 16, 13, 43, 45, 701808, tzinfo=utc)),
        ),
    ]
