# Generated by Django 2.0.3 on 2019-05-16 13:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dicomapp', '0003_auto_20190516_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 5, 16, 13, 47, 32, 486975, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='admission',
            name='time',
            field=models.TimeField(default=datetime.datetime(2019, 5, 16, 13, 47, 32, 486975, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 5, 16, 13, 47, 32, 494975, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='endTime',
            field=models.TimeField(default=datetime.datetime(2019, 5, 16, 13, 47, 32, 494975, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='startTime',
            field=models.TimeField(default=datetime.datetime(2019, 5, 16, 13, 47, 32, 494975, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='medicaltest',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 5, 16, 13, 47, 32, 494975, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patientfiles',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 16, 13, 47, 32, 499007, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 5, 16, 13, 47, 32, 491007, tzinfo=utc)),
        ),
    ]
