# Generated by Django 2.0.3 on 2019-05-16 13:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dicomapp', '0004_auto_20190516_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='date',
            field=models.DateField(default=datetime.date(2019, 5, 16)),
        ),
        migrations.AlterField(
            model_name='admission',
            name='time',
            field=models.TimeField(default=datetime.datetime(2019, 5, 16, 13, 52, 54, 97718, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.date(2019, 5, 16)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='endTime',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='startTime',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='medicaltest',
            name='date',
            field=models.DateField(default=datetime.date(2019, 5, 16)),
        ),
        migrations.AlterField(
            model_name='patientfiles',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 16, 13, 52, 54, 109591, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='date',
            field=models.DateField(default=datetime.date(2019, 5, 16)),
        ),
    ]
