# Generated by Django 2.0.3 on 2019-05-16 19:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dicomapp', '0006_auto_20190517_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='contactName',
            new_name='emergencycontactName',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='contactNumber',
            new_name='emergencycontactNumber',
        ),
        migrations.AlterField(
            model_name='admission',
            name='time',
            field=models.TimeField(default=datetime.datetime(2019, 5, 16, 19, 34, 8, 649387, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patientfiles',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 16, 19, 34, 8, 658387, tzinfo=utc)),
        ),
    ]
