# Generated by Django 2.0.3 on 2019-05-16 19:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dicomapp', '0007_auto_20190517_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='time',
            field=models.TimeField(default=datetime.datetime(2019, 5, 16, 19, 41, 24, 206003, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Radiologist'), (2, 'Neurologist'), (3, 'Neurosergeon'), (4, 'Physician'), (5, 'Pathologist'), (6, 'Orthopedics'), (7, 'General Surgery'), (8, 'Internal Medicine'), (9, 'Paedriatics'), (10, 'ENT')], max_length=50),
        ),
        migrations.AlterField(
            model_name='patientfiles',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 16, 19, 41, 24, 217001, tzinfo=utc)),
        ),
    ]
