# Generated by Django 2.0.3 on 2019-05-16 19:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dicomapp', '0009_auto_20190517_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='time',
            field=models.TimeField(default=datetime.datetime(2019, 5, 16, 19, 48, 33, 146323, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Aetna'), (2, 'United HealthCare'), (3, 'Humana'), (4, 'Celtic Healthcare'), (5, 'BlueCross BlueShield'), (6, 'Cigna'), (7, 'Emblem Healthcare'), (8, 'Amerigroup'), (9, 'Kaiser Permanente'), (10, 'Wellpoint')], max_length=50),
        ),
        migrations.AlterField(
            model_name='patientfiles',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 16, 19, 48, 33, 155322, tzinfo=utc)),
        ),
    ]
