# Generated by Django 2.0.3 on 2019-05-16 21:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dicomapp', '0010_auto_20190517_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='time',
            field=models.TimeField(default=datetime.datetime(2019, 5, 16, 21, 44, 51, 300480, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patientfiles',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 16, 21, 44, 51, 310477, tzinfo=utc)),
        ),
    ]
