# Generated by Django 2.2.3 on 2019-07-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Malaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=32)),
                ('origin', models.CharField(max_length=256)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
